### ISSUE TITLE
App won't run

### ISSUE THREAD

**Issue by Gh0stGames** [Bombg/SassBot#11]
When I try to use the run.py script I get these errors, I followed all of the setup instructions.

```2024-06-21 05:34:22,843 hikari.tanjun.clients: Client callback raised exception
Traceback (most recent call last):
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/clients.py", line 463, in _wrap_client_callback
    await client.injector.call_with_async_di(callback, *args)
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 225, in call_with_async_di
    return typing.cast(_T, await BasicContext(self).call_with_async_di(callback, *args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 331, in call_with_async_di
    return typing.cast(_T, await self._injection_client.call_with_ctx_async(self, callback, *args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 241, in call_with_ctx_async
    return typing.cast(_T, await result)
                           ^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/clients.py", line 496, in __call__
    await self.client.declare_global_commands(
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/clients.py", line 1374, in declare_global_commands
    return await self.declare_application_commands(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/clients.py", line 1536, in declare_application_commands
    application = application or self._cached_application_id or await self.fetch_rest_application_id()
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/clients.py", line 2445, in fetch_rest_application_id
    self._cached_application_id = hikari.Snowflake(await self._rest.fetch_application())
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 2162, in fetch_application
    response = await self._request(route)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 732, in _request
    await aio.first_completed(request_task, self._close_event.wait())
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/internal/aio.py", line 135, in first_completed
    await next(iterator)
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 615, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 905, in _perform_request
    raise await net.generate_error_response(response)
hikari.errors.UnauthorizedError: Unauthorized 401: '401: Unauthorized' for https://discord.com/api/v10/oauth2/applications/@me
E 2024-06-21 05:34:22,997 hikari.event_manager: an exception occurred handling an event (StartingEvent)
Traceback (most recent call last):
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/clients.py", line 1327, in _on_starting
    await self.open()
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/clients.py", line 2393, in open
    user = await self._rest.fetch_my_user()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 2053, in fetch_my_user
    response = await self._request(route)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 732, in _request
    await aio.first_completed(request_task, self._close_event.wait())
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/internal/aio.py", line 135, in first_completed
    await next(iterator)
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 615, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 905, in _perform_request
    raise await net.generate_error_response(response)
hikari.errors.UnauthorizedError: Unauthorized 401: '401: Unauthorized' for https://discord.com/api/v10/users/@me
I 2024-06-21 05:34:23,153 hikari.bot: bot requested to shut down
E 2024-06-21 05:34:23,154 hikari.event_manager: an exception occurred handling an event (StoppingEvent)
Traceback (most recent call last):
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/gateway_bot.py", line 812, in run
    loop.run_until_complete(
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/gateway_bot.py", line 927, in start
    requirements = await self._rest.fetch_gateway_bot_info()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 2030, in fetch_gateway_bot_info
    response = await self._request(route)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 732, in _request
    await aio.first_completed(request_task, self._close_event.wait())
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/internal/aio.py", line 135, in first_completed
    await next(iterator)
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 615, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 905, in _perform_request
    raise await net.generate_error_response(response)
hikari.errors.UnauthorizedError: Unauthorized 401: '401: Unauthorized' for https://discord.com/api/v10/gateway/bot

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/clients.py", line 1330, in _on_stopping
    await self.close()
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/clients.py", line 2357, in close
    await asyncio.gather(*(component.close() for component in self._components.copy().values()))
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/components.py", line 1392, in close
    raise RuntimeError("Component isn't active")
RuntimeError: Component isn't active
I 2024-06-21 05:34:23,156 hikari.bot: bot shut down successfully
I 2024-06-21 05:34:23,157 hikari.bot: successfully terminated
Traceback (most recent call last):
  File "/home/justanw/Documents/SassBot/run.py", line 13, in <module>
    build_bot().run()
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/gateway_bot.py", line 812, in run
    loop.run_until_complete(
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/gateway_bot.py", line 927, in start
    requirements = await self._rest.fetch_gateway_bot_info()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 2030, in fetch_gateway_bot_info
    response = await self._request(route)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 732, in _request
    await aio.first_completed(request_task, self._close_event.wait())
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/internal/aio.py", line 135, in first_completed
    await next(iterator)
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 615, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/hikari/impl/rest.py", line 905, in _perform_request
    raise await net.generate_error_response(response)
hikari.errors.UnauthorizedError: Unauthorized 401: '401: Unauthorized' for https://discord.com/api/v10/gateway/bot
```

**Comment by Bombg** [comment]
looks like you possibly haven't supplied a bot token. Did you create a sub folder called secrets and put the bot token in a file named 'token'? 

Example: https://imgur.com/yfkZQzC

**Comment by Bombg** [comment]
If its not a token issue, make sure you set up the invite link correctly with the right permissions.

Example: https://i.imgur.com/Ew2Me7p.png

**Comment by Gh0stGames** [comment]
I did the bot token. I'll double check my permissions though.

**Comment by Gh0stGames** [comment]
I got it to work! Turns out it was a token issue after all, just had to reset my token and get a new one. Thanks for the help!

**Comment by Gh0stGames** [comment]
Okay so it ran but then after awhile started spitting out some more errors.

```
Traceback (most recent call last):
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/schedules.py", line 338, in _execute
    await client.call_with_async_di(self._callback)
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 225, in call_with_async_di
    return typing.cast(_T, await BasicContext(self).call_with_async_di(callback, *args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 331, in call_with_async_di
    return typing.cast(_T, await self._injection_client.call_with_ctx_async(self, callback, *args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 241, in call_with_ctx_async
    return typing.cast(_T, await result)
                           ^^^^^^^^^^^^
  File "/home/justanw/Documents/SassBot/plugins/checks.py", line 87, in checkOnlyfans
    await platformChecker(Onlyfans.isModelOnline, Notifications.OFNotification,ofUserName,"onlyfans",rest)
  File "/home/justanw/Documents/SassBot/plugins/checks.py", line 67, in platformChecker
    db.setRerun(isRerun, platformName)
  File "/home/justanw/Documents/SassBot/Database.py", line 220, in setRerun
    self.checkAddRerunCols()
  File "/home/justanw/Documents/SassBot/Database.py", line 569, in checkAddRerunCols
    cur.execute('''ALTER TABLE stream ADD rerun_ping INTEGER ''')
sqlite3.OperationalError: no such table: stream
```
```
Traceback (most recent call last):
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/schedules.py", line 338, in _execute
    await client.call_with_async_di(self._callback)
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 225, in call_with_async_di
    return typing.cast(_T, await BasicContext(self).call_with_async_di(callback, *args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 331, in call_with_async_di
    return typing.cast(_T, await self._injection_client.call_with_ctx_async(self, callback, *args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 241, in call_with_ctx_async
    return typing.cast(_T, await result)
                           ^^^^^^^^^^^^
  File "/home/justanw/Documents/SassBot/plugins/checks.py", line 185, in changeStatus
    subathon,subStart,subEnd = db.getSubathonStatusClean()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/Documents/SassBot/Database.py", line 310, in getSubathonStatusClean
    sub = self.getSubathonStatus()
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/Documents/SassBot/Database.py", line 303, in getSubathonStatus
    cur.execute(exeString)
sqlite3.OperationalError: no such table: subathon
error when checking if col exists, perhaps no data yet
Traceback (most recent call last):
  File "/home/justanw/.local/lib/python3.11/site-packages/tanjun/schedules.py", line 338, in _execute
    await client.call_with_async_di(self._callback)
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 225, in call_with_async_di
    return typing.cast(_T, await BasicContext(self).call_with_async_di(callback, *args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 331, in call_with_async_di
    return typing.cast(_T, await self._injection_client.call_with_ctx_async(self, callback, *args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/.local/lib/python3.11/site-packages/alluka/_client.py", line 241, in call_with_ctx_async
    return typing.cast(_T, await result)
                           ^^^^^^^^^^^^
  File "/home/justanw/Documents/SassBot/plugins/checks.py", line 208, in checkOnlineTime
    online = StaticMethods.checkOnline(db)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/Documents/SassBot/StaticMethods.py", line 193, in checkOnline
    cbLastOnlineMessage,cbStreamStartTime,cbStreamEndTime, cbIsRerun = db.getPlatformsRowValues('chaturbate')
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justanw/Documents/SassBot/Database.py", line 260, in getPlatformsRowValues
    self.checkAddPlatformRow(platformName)
  File "/home/justanw/Documents/SassBot/Database.py", line 276, in checkAddPlatformRow
    cur.execute('INSERT INTO platforms (platform_name, last_online_message,last_stream_start_time,last_stream_end_time) VALUES (?,?,?,?)',rowVals)
sqlite3.OperationalError: no such table: platforms
```

**Comment by Bombg** [comment]
Generate the database with 'python GenerateDatabase.py' or 'python3 GenerateDatabase.py'

**Comment by Gh0stGames** [comment]
> Generate the database with 'python GenerateDatabase.py' or 'python3 GenerateDatabase.py'

Oh yeah... I'm an idiot. Sorry I'm running on only an hour of sleep. I'm sure this should do the trick but I'll confirm first before I close the thread.
