### ISSUE TITLE
Not works for me

### ISSUE THREAD

**Issue by l0g4n1337** [Bombg/SassBot#2]
`W 2023-09-06 22:17:49,741 hikari.ux: You are running on optimization level 0 (no optimizations), which may slow down your application. For production, consider using at least level 1 optimization by passing `-O` to the python call.
I 2023-09-06 22:17:49,782 hikari.tanjun.clients: Event-managed client initialised with the following components: cache, event manager, rest, shard manager
I 2023-09-06 22:17:49,782 hikari.tanjun.clients: Loading from plugins.checks
I 2023-09-06 22:17:49,966 hikari.tanjun.clients: Loading from plugins.commands
I 2023-09-06 22:17:50,529 hikari.tanjun.clients: Loading from plugins.listeners
I 2023-09-06 22:17:50,579 hikari.ux: A newer version of hikari is available, consider upgrading to 2.0.0.dev120
I 2023-09-06 22:17:51,044 hikari.tanjun.clients: Skipping bulk declare for guild 653896702150967316 application commands since they're already declared
I 2023-09-06 22:17:51,398 hikari.bot: you can start 998 sessions before the next window which starts at 2023-09-07 20:35:27.643900+02:00; planning to start 1 session... 
I 2023-09-06 22:17:51,798 hikari.gateway.0: shard is ready: 1 guilds, .G#2749 (942322747273527376), session '56ea8acaccf6209c34e17b30fbcab4a8' on v10 gateway
I 2023-09-06 22:17:51,799 hikari.bot: started successfully in approx 1.27 seconds
/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 96, in start
    path = SeleniumManager.driver_location(browser)
  File "/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 68, in driver_location
    result = SeleniumManager.run(args)
  File "/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 85, in run
    raise WebDriverException(f"Unsuccessful command executed: {args}")
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: ('/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager', '--browser', 'chrome')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
  File "/home/container/.local/lib/python3.10/site-packages/tanjun/schedules.py", line 338, in _execute
    await client.call_with_async_di(self._callback)
  File "/home/container/.local/lib/python3.10/site-packages/alluka/_client.py", line 225, in call_with_async_di
    return typing.cast(_T, await BasicContext(self).call_with_async_di(callback, *args, **kwargs))
  File "/home/container/.local/lib/python3.10/site-packages/alluka/_client.py", line 331, in call_with_async_di
    return typing.cast(_T, await self._injection_client.call_with_ctx_async(self, callback, *args, **kwargs))
  File "/home/container/.local/lib/python3.10/site-packages/alluka/_client.py", line 241, in call_with_ctx_async
    return typing.cast(_T, await result)
  File "/home/container/plugins/checks.py", line 83, in checkFansly
    await platformChecker(Fansly.isModelOnline, Notifications.FansNotification,fansUserName,"fansly",rest)
  File "/home/container/plugins/checks.py", line 33, in platformChecker
    isOnline, title, thumbUrl, icon = await asyncio.get_running_loop().run_in_executor(None,isOnlineFunc,userName)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/container/checkers/Fansly.py", line 15, in isModelOnline
    driver = driverCreator.createDriver()
  File "/home/container/SeleniumDriverCreator.py", line 27, in createDriver
    driver = webdriver.Chrome(options=chrome_options)
  File "/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 99, in start
    raise err
  File "/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 90, in start
    self._start_process(self.path)
  File "/home/container/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 212, in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home`

**Comment by Bombg** [comment]
The bot relies on chrome/chrome driver to be installed so make sure you have both installed.

**Comment by l0g4n1337** [comment]
Fixed it works, 
Can it work with multiple accounts?

**Comment by Bombg** [comment]
you can add multiple accounts per platform (the comments on the constants file shows how to do it). But there's currently a limitation where it will only show an alert for one account per platform at a time. So for example, if two onlyfans streams go up at the same time , an alert will only be shown for the first one. But you can have alerts go off for every other platform at the same time, if that makes sense. I want to fix this limitation in the future, but for now this is how it is.

**Comment by Bombg** [comment]
I should add I just added the ability to have multiple accounts per platform just the other day, so if you're using a clone that's more than a day old then you'll need to pull the new changes to use multiple accounts per platform.
